. $psScriptRoot\GetCPUInfo.ps1
. $psScriptRoot\TestServerConnection.ps1
. $psScriptRoot\GetPrinters.ps1
. $psScriptRoot\GetLastBootUpTime.ps1
. $psScriptRoot\GetAllWindowsServices.ps1
. $psScriptRoot\GetOSInfo.ps1
. $psScriptRoot\GetRAMInfo.ps1
. $psScriptRoot\GetNetworkInfo.ps1
. $psScriptRoot\GetComputerSystemInfo.ps1
. $psScriptRoot\GetFolderSize.ps1
. $psScriptRoot\UseWS.ps1